---
- name: "Start or restart container: {{ container_name }}"
  ansible.builtin.systemd_service:
    name: "{{ container_instance_name | default(container_name) }}.service"
    state: restarted
    daemon_reload: true
  when: container_start_service
