---
- name: App container
  hosts: all
  tasks:
  - name: Install unit file for app
    ansible.builtin.template:
      src: app@.container.j2
      dest: /etc/containers/systemd/app@.container
  # TODO: Login to registry!
  - name: Enable app service in systemd
    ansible.builtin.systemd_service:
      name: app@1.service
      enabled: true
      state: started
      daemon_reload: true
