---
- name: App container
  hosts: all
  tasks:
  - name: Pull app container
    containers.podman.podman_image:
      name: '{{ app_docker_image }}'
      state: present
  - name: Install unit file for app
    ansible.builtin.template:
      src: app@.container.j2
      dest: /etc/containers/systemd/app@.container
  - name: Enable app service in systemd
    ansible.builtin.systemd_service:
      name: app@1.service
      enabled: true
      state: started
      daemon_reload: true
  - name: Add block to Caddyfile
    ansible.builtin.blockinfile:
      path: /srv/volumes/caddy-config/Caddyfile
      prepend_newline: true
      append_newline: true
      block: |
        {{ app_domain }} {
            reverse_proxy * app:3000
        }
    register: result_caddy_conf
  - name: Restart Caddy
    ansible.builtin.systemd_service:
      name: caddy.service
      state: restarted
    when: result_caddy_conf.changed
