---
- name: App container
  hosts: all
  tasks:
    - name: Pull app container
      containers.podman.podman_image:
        name: '{{ app_docker_image }}'
        state: present
    - name: Install unit file for app
      ansible.builtin.template:
        src: vpslite-app@.container.j2
        dest: /etc/containers/systemd/vpslite-app@.container
        mode: '0600'
    - name: Install target file for managing app instances
      ansible.builtin.copy:
        src: vpslite-app.target
        dest: /etc/systemd/system/vpslite-app.target
        mode: '0600'
    - name: Enable app target in systemd
      ansible.builtin.systemd_service:
        name: vpslite-app.target
        enabled: true
        state: started
        daemon_reload: true
    - name: Add block to Caddyfile
      ansible.builtin.blockinfile:
        path: /srv/volumes/caddy-config/Caddyfile
        marker: "# {mark} ANSIBLE MANAGED BLOCK - app playbook"
        block: |
          {{ app_domain }} {
              reverse_proxy * app:3000
          }
      notify: Restart Caddy
  handlers:
    - name: Restart Caddy
      ansible.builtin.systemd_service:
        name: vpslite-caddy.service
        state: restarted
