---
- name: System update
  hosts: all
  vars_files: const/versions.yaml
  tasks:
    - name: Ensure all packages are upgraded
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
    - name: Install unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
    - name: Enable unattended-upgrades
      ansible.builtin.copy:
        src: 20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0600'

- name: System users
  hosts: all
  vars_files: const/versions.yaml
  tasks:
    - name: Create system group
      ansible.builtin.group:
        name: vpslite
        system: true
    - name: Create system user for running containers
      ansible.builtin.user:
        name: vpslite-container
        system: true
        group: vpslite

- name: Podman
  hosts: all
  vars_files: const/versions.yaml
  tasks:
    - name: Install Podman
      ansible.builtin.apt:
        name: podman
        state: present
    - name: Install network definition for web
      ansible.builtin.copy:
        src: web.network
        dest: /etc/containers/systemd/web.network
        mode: '0600'
    - name: Start web network
      ansible.builtin.systemd_service:
        name: web-network
        enabled: true
        state: started
        daemon_reload: true
    - name: Install network definition for infra
      ansible.builtin.copy:
        src: infra.network
        dest: /etc/containers/systemd/infra.network
        mode: '0600'
    - name: Start infra network
      ansible.builtin.systemd_service:
        name: infra-network
        enabled: true
        state: started
        daemon_reload: true

- name: Caddy reverse proxy
  hosts: all
  vars_files: const/versions.yaml
  tasks:
    - name: Install Caddy container
      ansible.builtin.include_role:
        name: container
      vars:
        container_name: vpslite-caddy
        container_create_volumes:
          - /srv/volumes/caddy-config
          - /srv/volumes/caddy-data
        container_start_service: false
    - name: Make config file for caddy
      ansible.builtin.copy:
        src: Caddyfile
        dest: /srv/volumes/caddy-config/Caddyfile
        mode: '0600'
        owner: vpslite-container
        group: vpslite
        force: false
      notify: Restart Caddy
    - name: Make sure caddy image is available
      containers.podman.podman_image:
        name: '{{ ver_caddy_image }}'
        state: present
    - name: Enable caddy service in systemd
      ansible.builtin.systemd_service:
        name: vpslite-caddy.service
        enabled: true
        state: started
        daemon_reload: true
  handlers:
    - name: Restart Caddy
      ansible.builtin.systemd_service:
        name: vpslite-caddy.service
        state: restarted
      when: caddy_conf.changed
