- name: Redis
  hosts: all
  vars_files: const/versions.yaml
  tasks:
    - name: Create redis container unit file
      ansible.builtin.include_role:
        name: container
      vars:
        container_name: vpslite-redis
        container_create_volumes:
          - /srv/volumes/redis-config
          - /srv/volumes/redis-data
        container_drop_files:
          - src: redis.conf
            dest: /srv/volumes/redis-config/redis.conf
    - name: Install backup provider for redis
      ansible.builtin.include_role:
        name: backup_provider
      vars:
        backup_provider_name: redis
