- name: Docker Image Registry
  hosts: all
  vars_files: const/versions.yaml
  tasks:
  - name: Install unit file for registry
    ansible.builtin.template:
      src: registry.container.j2
      dest: /etc/containers/systemd/registry.container
  - name: Prepare data volume for registry
    ansible.builtin.file:
      path: /srv/volumes/registry-data
      state: directory
      mode: '0700'
  - name: Enable registry service in systemd
    ansible.builtin.systemd_service:
      name: registry.service
      enabled: true
      state: started
      daemon_reload: true
  - name: Hash password for basic auth to registry
    ansible.builtin.command:
      argv:
        - podman
        - run
        - '--rm'
        - '{{ ver_caddy_image }}'
        - caddy
        - hash-password
        - '-p' 
        - '{{ registry_password }}'
    register: result_registry_password_hash
  - name: Add block to Caddyfile
    ansible.builtin.blockinfile:
      path: /srv/volumes/caddy-config/Caddyfile
      prepend_newline: true
      append_newline: true
      block: |
        {{ registry_domain }} {
            basic_auth {
              dev {{ result_registry_password_hash.stdout }}
            }
            reverse_proxy * registry:5000
        }
    register: result_caddy_conf
  - name: Restart Caddy
    ansible.builtin.systemd_service:
      name: caddy.service
      state: restarted
    when: result_caddy_conf.changed
  - name: Login to local registry
    containers.podman.podman_login:
      username: dev
      password: '{{ registry_password }}'
      registry: '{{ registry_domain }}'
